// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzrrdrMRILsqichTZTFuqZqhxqKaNoAJc',
    appId: '1:238227633005:web:0b525fae3359ed3a23e064',
    messagingSenderId: '238227633005',
    projectId: 'xgen-machine-task',
    authDomain: 'xgen-machine-task.firebaseapp.com',
    storageBucket: 'xgen-machine-task.firebasestorage.app',
    measurementId: 'G-5ZTMCYM4BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ZX-_vVYGzhdHS0g9No_zYmi9vYftewE',
    appId: '1:238227633005:android:691f57186a79befe23e064',
    messagingSenderId: '238227633005',
    projectId: 'xgen-machine-task',
    storageBucket: 'xgen-machine-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDKIYpbWh-0Ucqlouz38U6RNjFJVSxDvQ',
    appId: '1:238227633005:ios:73cca10dc278694523e064',
    messagingSenderId: '238227633005',
    projectId: 'xgen-machine-task',
    storageBucket: 'xgen-machine-task.firebasestorage.app',
    iosBundleId: 'com.example.xgenMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDKIYpbWh-0Ucqlouz38U6RNjFJVSxDvQ',
    appId: '1:238227633005:ios:73cca10dc278694523e064',
    messagingSenderId: '238227633005',
    projectId: 'xgen-machine-task',
    storageBucket: 'xgen-machine-task.firebasestorage.app',
    iosBundleId: 'com.example.xgenMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzrrdrMRILsqichTZTFuqZqhxqKaNoAJc',
    appId: '1:238227633005:web:88ca9377d2a1679423e064',
    messagingSenderId: '238227633005',
    projectId: 'xgen-machine-task',
    authDomain: 'xgen-machine-task.firebaseapp.com',
    storageBucket: 'xgen-machine-task.firebasestorage.app',
    measurementId: 'G-K6SC3K93ZP',
  );
}
